#This file was originally generated by PyScripter's unitest wizard

import unittest
import proxy
import Queue

class TestGlobalFunctions(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testproxy(self):
        host = ('w3school.com.cn',80)
        q=Queue.Queue()
        conn = debug_conn()
        req='GET http://w3school.com.cn/index.html HTTP/1.1\r\nHost:w3school.com.cn\r\n\r\n'
        proxy.proxy(host, conn, conn.error, req, q)

class debug_conn():
    def send(a):
        print """========
        %s
        ========"""%repr(a)
    def error(v,s):
        print 'code: %s, message: %s\n'%(v,s)

if __name__ == '__main__':
    unittest.main()
